### ISSUE TITLE
Omniledger

### ISSUE THREAD

**Issue by chenhuan14** [dedis/student_17_bftcosi#1]
Hello, i'm a researcher in sharding technology, i have read your paper about OmniLegder and very intreated in it , would you give me the source code. Thank you very much . my email address is chenhuan245@gmail.com

**Comment by Racater** [comment]
Hello,
Omniledger is still in development and will be available in [Cothority](https://github.com/dedis/cothority) in 2018.
The implementation work is done in [here](https://github.com/dedis/student_18_omniledger) and will be put into Cothority once ready
